### ISSUE TITLE
I think this is written incorrectly

### ISSUE THREAD

**Issue by gonghanling** [devcoons/iso15765-canbus#18]
https://github.com/devcoons/iso15765-canbus/blob/460db1fbb3bc8e21b7d6897c8aa4e0f3d55a151d/src/lib_iso15765.c#L370

I think this piece should not be N_ADM_EXTENDED, but N_ADM_FIXED.
And when defining the enumeration of this block, the two comments FIX and EXTEN are mixed up.
https://github.com/devcoons/iso15765-canbus/blob/460db1fbb3bc8e21b7d6897c8aa4e0f3d55a151d/src/lib_iso15765.h#L108

**Comment by devcoons** [comment]
> https://github.com/devcoons/iso15765-canbus/blob/460db1fbb3bc8e21b7d6897c8aa4e0f3d55a151d/src/lib_iso15765.c#L370
> 
> I think this piece should not be N_ADM_EXTENDED, but N_ADM_FIXED. And when defining the enumeration of this block, the two comments FIX and EXTEN are mixed up.
> 
> https://github.com/devcoons/iso15765-canbus/blob/460db1fbb3bc8e21b7d6897c8aa4e0f3d55a151d/src/lib_iso15765.h#L108

Hi @gonghanling, thank you very much for your observation. Regarding the first part with the switch-case, i need to verify better according to the ISO, however, you are correct about the comments. I'll fix it asap! Thanks again!

**Comment by gonghanling** [comment]
Sorry, I didn't notice it. It can be seen in 15765-2 that Extended addressing, Byte1 needs to be filled in N_TA. So no problem.
