### ISSUE TITLE
Flow Control Management?

### ISSUE THREAD

**Issue by TheAlgorythm** [devcoons/iso15765-canbus#19]
What is the intended solution for sending flow control frames on a received first frame? I haven't found any option to configure on which IDs it should reply.
Or is it intended to implement it manually in `usdata_indication`?

**Comment by mitkodev** [comment]
Hey @TheAlgorythm 
based on my experience, when you initially send a frame and you enqueue a response data that is actually the first frame from a multiframe response, the library will automatically prepare the address and the control flow frame and will call your send_frame method to send it. So in the end you dont have to do anything manually, you'll just receive in your data callback when the full frame data is parsed.
