### ISSUE TITLE
Time overflow risk

### ISSUE THREAD

**Issue by konglualualu** [devcoons/iso15765-canbus#23]
The n_cs is a 32-bit number in ms. If the time overflows, the state machine of ih->out.pdu.n_pci.pt will be stuck in the N_PCI_T_CF state.
<img width="1442" alt="image" src="https://github.com/user-attachments/assets/ea5403f4-38c3-4054-9748-59911e3810ec">

**Comment by devcoons** [comment]
Correction applied. Thank you

**Comment by konglualualu** [comment]
The new way still seems to be risky. Actually we have encountered such a situation，n_cs may be a big number like 0xFFFFFFFF-1（just about 50 days in ms）, stmin is 5, then no matter what get_ms() return, get_ms() - stmin will be smaller than n_cs.
<img width="873" alt="image" src="https://github.com/user-attachments/assets/5fd5c4e7-83e0-4a6a-b5f3-18123c22a3e1">

**Comment by devcoons** [comment]
The new update seems that resolves this situation

**Comment by konglualualu** [comment]
The 2nd update may cause the CF interval to not meet the requirements of stmin when the time overflows. However, the probability is very small and so it is barely acceptable. Thank you.
