### ISSUE TITLE
Wrong interpretation of BlockSize parameter.

### ISSUE THREAD

**Issue by ManvydasVaitkus** [devcoons/iso15765-canbus#24]
Hi,
in my understanding this library has a bug when setting flag to wait for Flow Control message. 
![image](https://github.com/user-attachments/assets/77dac85d-39a1-4c94-9de5-8ef2b55dcfae)
BlockSize can be up to 255, and in my given screenshot it checks against sequence number, which are unrelated. 

Citation from standard: "(01h-FFh) This range of BS parameter values shall be used to indicate to the sender the maximum number of ConsecutiveFrames that can be received without an intermediate FC frame from the receiving network entity."  Correct me if I am wrong.

**Comment by devcoons** [comment]
Hi, you're correct in your understanding. 

The BS parameter indicates the maximum number of Consecutive Frames (CFs) that can be received without waiting for an intermediate Flow Control (FC) frame. 

In the code, the Sequence Number of the current CF is checked continuously, and when the number of consecutive frames reaches the value specified by the BS parameter, the system expects a Flow Control frame to be sent. This ensures that the maximum allowed number of CFs is respected before an FC frame is required.

**Example with BS = 5:**
Let's say the BS parameter is set to 5, meaning the receiver can accept up to 5 consecutive frames without requiring a Flow Control (FC) frame. The system will process the first five consecutive frames, checking the sequence number each time.

Frame 1: Sequence Number SN:1 (no FC needed)
Frame 2: Sequence Number SN:2 (no FC needed)
Frame 3: Sequence Number SN:3 (no FC needed)
Frame 4: Sequence Number SN:4 (no FC needed)
Frame 5: Sequence Number SN:5 (no FC needed)

Once Frame 5 is received, the system has processed 5 consecutive frames. According to the BS value of 5, the next frame (Frame 6) should be a Flow Control frame before processing any further data.

Frame 6: Flow Control

Frame 7: Sequence Number SN:1 (no FC needed)
Frame 8: Sequence Number SN:2 (no FC needed)
Frame 9: Sequence Number SN:3 (no FC needed)
Frame 10: Sequence Number SN:4 (no FC needed)
Frame 11: Sequence Number SN:5 (no FC needed)


This ensures that no more than 5 consecutive frames are received without an FC frame in between.

**Comment by ManvydasVaitkus** [comment]
And what happens if I give it a value of 200? Which is fully valid value by standard. SequenceNumber should go up until 0x0F. So It will never wait for FC. Only place where this flag is set besides my screenshot is after FF.

**Comment by ManvydasVaitkus** [comment]
Also It should be checked against BlockSize provided by packet receiver (via FC), not by configured in protocol.

**Comment by devcoons** [comment]
Thank you for your observation, the issue is fixed

**Comment by ManvydasVaitkus** [comment]
Thank you for fast responses, it still works incorrectly.  It resets SequenceNumber after reception of FC, while it should just continue with it. In standard "9.6.4.3 SequenceNumber (SN) parameter definition" it has part where it says: "that the SN value shall not be affected by any FlowControl (FC) frame;". From my testing: 
![image](https://github.com/user-attachments/assets/4cec8a5e-a32c-429b-90e2-bcd4b299a073)
